# Generated by Django 3.1 on 2021-07-06 08:15

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('quickstart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='image',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='%Y/%m/%d'),
            preserve_default=False,
        ),
    ]
